name: lint

on:
  push:
  pull_request:
    types: [ opened, synchronize ]

jobs:
  check:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [ '3.10' ]

    name: check ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install deps
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -U -r dev-requirements.txt

      - name: Setup node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install pyright
        run: |
          npm install -g pyright

      - name: Run pyright
        run: |
          pyright

      - name: Style check
        run: |
          black --check --verbose umn_async_utils

      - name: Import check
        run: |
          isort --check umn_async_utils

      - name: Verify No CLRF line endings.
        run: >
          ! $(find . ! -path "./.git/*" -not -type d -exec file "{}" ";" |& grep -q " CRLF ")
